config/routes.rb
PetsApp::Application.routes.draw do
  
  root to: 'records#new'
  resources :records

end

app/models/owner.rb
# == Schema Information
#
# Table name: owners
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  phone      :string(255)
#  email      :string(255)
#  address    :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Owner < ActiveRecord::Base
  attr_accessible :id, :address, :email, :name, :phone
  has_many :pets, :dependent => :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /^(\(\d{3}\)|\d{3})-?\d{3}-?\d{4}$/                   #/^[\d() -]+/


  validates :name, presence: true, length: { maximum:50 }
  validates :address, presence: true, length: { maximum:300 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX, :message => 'is invalid. Please use this format: "(XXX)-XXX-XXXX"' } 

end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id          :integer         not null, primary key
#  owner_id    :integer
#  name        :string(255)
#  age         :string(255)
#  pet_type_id :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Pet < ActiveRecord::Base
  belongs_to :owner
  belongs_to :pet_type
  attr_accessible :age, :name, :pet_type_id, :owner_id

  validates :name, presence: true, length: { maximum:50 }
  validates :age, presence: true, length: { maximum:50 }
  validates :pet_type_id, presence: true

end

app/models/pet_type.rb
# == Schema Information
#
# Table name: pet_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class PetType < ActiveRecord::Base
  attr_accessible :name, :id
  has_many :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    redirect_to root_path
  end

  def new
	@owner = Owner.new
	@pet = Array.new
	RecordsHelper::ALLOWED_PETS.times { |t| @pet[t] = Pet.new } 
	@pet_storage = Array.new unless defined?(@pet_storage)
	@pet_number_storage = 1 unless defined?(@pet_number_storage)  
  end

  def create
  	@owner = Owner.new(params[:owner])
  	@pet = Array.new
  	params[:number_of_pets].to_i.times { |t| @pet[t] = Pet.new(params[:pet][t]) }
  	pet_valid = (@pet.map { |t| t.valid? })

	if (@owner.valid? && pet_valid.all?)
	  @owner.save
	  @pet.each do |t|
	  	t.owner_id = @owner.id
	  	t.save
	  end
	  @pet_storage = Array.new
	  @pet_number_storage = 1
  	  flash[:success] = "Data saved successfully"
  	  redirect_to record_path(@owner)
    else
      @pet_storage = @pet
      @pet_number_storage = params[:number_of_pets]
      render 'new'
    end

  end

  def show
    @owner = Owner.find_by_id(params[:id])
    if @owner.nil?
      respond_to do |format|
        format.html
        format.json { render :json => {error: "This record does not exist"}.to_json }
      end
    else
      @pet = Pet.where("owner_id = ?", params[:id])
      @json_response = format_json_show
      respond_to do |format|
      	format.html
      	format.json { render :json => @json_response.to_json }
      end
    end
  end


  def format_json_show
  	@response = { id:@owner.id, name: @owner.name, email: @owner.email, phone:@owner.phone, address:@owner.address }
  	@response[:pets_owned] = @pet.map { |hash| { name: hash[:name], age: hash[:age], pet_type: (PetType.where("id = ?", hash[:pet_type_id])[0].name) }}
  	@response
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
  ALLOWED_PETS = 4

  def allowed_pets_options
  	(1..ALLOWED_PETS).map do |t|
  	  if (t>1)
  	  	text = "#{t} Pets"
  	  else
  	  	text = "#{t} Pet"
  	  end
  	  [text,t]
  	end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Pet Registration - By David Hemmat
	</small>
	<nav>
		<ul>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Pet Registration", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %></title>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/records/new.html.erb
<% provide(:title, 'Pet Registration') %>
<h1>Pet Registration</h1>
<hr>
<h2 class="left-subtitle">Owner information</h2>
<%= form_for @owner, :url => records_path do |f| %>
  <%= render 'shared/owner_form', :f => f %>
    <h2 class="left-subtitle">Pet Information</h2>
    <label>Number of pets</label>
	</br>
    <%= select_tag "number_of_pets", options_for_select(allowed_pets_options, @pet_number_storage), onchange:"show_pet_forms(this.value, #{RecordsHelper::ALLOWED_PETS});" %>
    <%= form_for @pet[0], :url => records_path do |f2| %>
	    <% RecordsHelper::ALLOWED_PETS.times do |t| %>
	    	<%= render 'shared/pet_form', :t => t, :f2 => f2 %>
	    <% end %>
	    <hr>
	    <div class="center">
    		<%= submit_tag("Submit", class: "btn bt1n-large btn-primary") %>
    	</div>
    <% end %>
	</br>
<% end %>

app/views/records/show.html.erb
<% if @owner.nil? %>
	<% provide(:title, 'Pet Registration: Record does not exist') %>
	<h1>Sorry, this record does not exist</h1>
	<h2>Please try searching for another record</h2>
<% else %>
	<% provide(:title, 'Pet Registration') %>
	<h1>Registered information</h1>
	<hr>
	<h2 class="left-subtitle">Personal information</h2>
	<%= render 'shared/owner_registration_info' %>
	<hr>
	<h2 class="left-subtitle">Pets owned</h2>
	<%= render 'shared/pet_registration_info' %>
	<hr>
	<div class="center">
		<%= link_to "Create another record", root_path, class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/records/show.json.erb
{
	"Name": "<%@owner.name%>",
	"Phone": "<%@owner.phone%>",
	"Email": "<%@owner.email%>",
	"Address": "<%@owner.address%>"
}

app/views/shared/_owner_error_messages.html.erb
<% unless @owner.nil? %>
	<% if @owner.errors.any? %>
		<div id="error_explanation">
			<div class="alert alert-error">
				The form contains <%= pluralize(@owner.errors.count, "error") %>.
			</div>
			<ul>
			<% @owner.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
<% end %>

app/views/shared/_owner_form.html.erb
<%= render 'shared/owner_error_messages' %>

<%= f.label :name %>&nbsp;
<%= f.label :phone %>&nbsp;
<%= f.label :email %>&nbsp;
<%= f.label :address %>&nbsp;
</br>
<%= f.text_field :name %>&nbsp;
<%= f.text_field :phone %>&nbsp;
<%= f.text_field :email %>&nbsp;
<%= f.text_field :address %>&nbsp;
<hr>

app/views/shared/_owner_registration_info.html.erb
<div class="owner-info">
	<dl>
  		<dt>Registration ID:</dt>
    		<dd id="owner-id"><%= @owner.id %></dd></br>
  		<dt>Name:</dt>
    		<dd id="owner-name"><%= @owner.name.to_s %></dd></br>
    	<dt>Phone:</dt>
    		<dd id="owner-phone"><%= @owner.phone %></dd></br>
    	<dt>Email:</dt>
    		<dd id="owner-email"><%= @owner.email %></dd></br>
    	<dt>Address:</dt>
    		<dd id="owner-address"><%= @owner.address %></dd></br>
	</dl>
</div>

app/views/shared/_owner_registration_information.html.erb
<div>
	<dl>
  		<dt>Registration ID:</dt>
    		<dd id="owner-id"><%= @owner.id %></dd></br>
  		<dt>Name:</dt>
    		<dd id="owner-name"><%= @owner.name.to_s %></dd></br>
    	<dt>Phone:</dt>
    		<dd id="owner-phone"><%= @owner.phone %></dd></br>
    	<dt>Email:</dt>
    		<dd id="owner-email"><%= @owner.email %></dd></br>
    	<dt>Address:</dt>
    		<dd id="owner-address"><%= @owner.address %></dd></br>
	</dl>
</div>

app/views/shared/_pet_error_messages.html.erb
<% unless @pet[t].nil? %>
	<% if @pet[t].errors.any? %>
		<div id="error_explanation">
			<div class="alert alert-error">
				The form contains <%= pluralize(@pet[t].errors.count, "error") %>.
			</div>
			<ul>
			<% @pet[t].errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
<% end %>

app/views/shared/_pet_form.html.erb
<div id='<%="pet-#{t+1}"%>' class="pet-block<%= '-visible' if (t+1)<=@pet_number_storage.to_i %>">
	<hr>
	<%= render 'shared/pet_error_messages', :t => t %> 
	<div class="pet-numeration"> 
		<h3 class="form-subtitle"><%="#{t+1})"%></h3>
	</div>
	<div class="pet-form-div">
	    <%= f2.label :name %>&nbsp;
	    <%= f2.label :age %>&nbsp;
	    <%= f2.label :pet_type_id, 'Type of pet'%>
	    </br>
	    <%= text_field_tag "pet[][name]", @pet_storage[t].try(:name) %>&nbsp;
	    <%= text_field_tag "pet[][age]", @pet_storage[t].try(:age) %>&nbsp;
	    <%= select_tag("pet[][pet_type_id]", options_from_collection_for_select(PetType.all, "id", "name", 
	    				@pet_storage[t].try(:pet_type_id)), :prompt => 'Select a pet type') %>
	</div>
</div>

app/views/shared/_pet_registration_info.html.erb
<% if defined?(@pet) %>
	<% @pet.count.times do |t| %>
		<div id='<%="pet-#{t+1}"%>'>
			<hr> 
			<div class="pet-numeration"> 
				<h3 class="form-subtitle"><%="#{t+1})"%></h3>
			</div>
			<div class="pet-info-div">
				<dl>
			  		<dt>Name:</dt>
			    		<dd id="pet-<%= "#{t+1}" %>-name"><%= @pet[t].name %></dd>
			    	<dt>Age:</dt>
			    		<dd id="pet-<%= "#{t+1}" %>-age"><%= @pet[t].age %></dd>
			    	<dt>Pet type:</dt>
			    		<dd id="pet-<%= "#{t+1}" %>-type"><%= (PetType.where("id = ?", @pet[t].pet_type_id))[0].name %></dd>
				</dl>
			</div>
		</div>
	<% end %>
<% end %>